### PR TITLE
Use AppID instead of BundleID

### LINKED ISSUE #7: BundleID not found on object of type SKTAppInfo
It looks like SKTAppInfo renamed `BundleID` to `AppID`. I just tried building and got this error: 
image 2018-08-28 at 12 18 57 pm

Updating it to `AppID` instead of `BundleID` fixes the issue. I'm using SKTCaptureObjC (1.0.151)

I'll send over a PR shortly.

### PR DESCRIPTION
**Pull request by jimmybaker**
Fixes #7

### CODE REVIEW

**Comment by jimmybaker** [comment]
@enthal Feel free to use this while we wait for a merge. :)

`"react-native-socket-mobile": "jimmybaker/react-native-socket-mobile#patch-1",`

**Comment by ferrannp** [comment]
Hi @jimmybaker, thanks for the PR!

Do we need to update this version then https://github.com/callstack-internal/react-native-socket-mobile/blob/master/ios/ReactNativeSocketMobile.podspec#L19?

Can you also update README/docs that reference to bundleID?

**Comment by brunoreis** [comment]
This is now a blocker to use the lib. I applied it manually and, besides this merge, the package is working very well. Thanks for the job.

**Comment by ferrannp** [comment]
Solved in another PR.

**Pull request closed without merging**
